FROM alpine:latest
RUN apk --no-cache add ca-certificates libc6-compat wget

WORKDIR /root/emergency-material-system/backend/internal/logistics
COPY logistics .

VOLUME ["/root/emergency-material-system/backend/internal/common/config"]

EXPOSE 8085

CMD ["./logistics"]
