// Package logistics provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package logistics

import (
	"time"
)

// Defines values for PostLogisticsTrackingJSONBodyStatus.
const (
	PostLogisticsTrackingJSONBodyStatusCancelled PostLogisticsTrackingJSONBodyStatus = "cancelled"
	PostLogisticsTrackingJSONBodyStatusCreated   PostLogisticsTrackingJSONBodyStatus = "created"
	PostLogisticsTrackingJSONBodyStatusDelivered PostLogisticsTrackingJSONBodyStatus = "delivered"
	PostLogisticsTrackingJSONBodyStatusInTransit PostLogisticsTrackingJSONBodyStatus = "in_transit"
	PostLogisticsTrackingJSONBodyStatusPicked    PostLogisticsTrackingJSONBodyStatus = "picked"
)

// Defines values for PutLogisticsTrackingIdJSONBodyStatus.
const (
	PutLogisticsTrackingIdJSONBodyStatusCancelled PutLogisticsTrackingIdJSONBodyStatus = "cancelled"
	PutLogisticsTrackingIdJSONBodyStatusCreated   PutLogisticsTrackingIdJSONBodyStatus = "created"
	PutLogisticsTrackingIdJSONBodyStatusDelivered PutLogisticsTrackingIdJSONBodyStatus = "delivered"
	PutLogisticsTrackingIdJSONBodyStatusInTransit PutLogisticsTrackingIdJSONBodyStatus = "in_transit"
	PutLogisticsTrackingIdJSONBodyStatusPicked    PutLogisticsTrackingIdJSONBodyStatus = "picked"
)

// Defines values for TrackingStatus.
const (
	Cancelled TrackingStatus = "cancelled"
	Created   TrackingStatus = "created"
	Delivered TrackingStatus = "delivered"
	InTransit TrackingStatus = "in_transit"
	Picked    TrackingStatus = "picked"
)

// Error defines model for Error.
type Error struct {
	// Error 错误信息
	Error *string `json:"error,omitempty"`
}

// PostLogisticsTrackingJSONBody defines model for PostLogisticsTrackingJSONBody.
type PostLogisticsTrackingJSONBody struct {
	// Description 物流追踪描述
	Description *string `json:"description,omitempty"`

	// RequestId 关联的需求申报ID
	RequestId int `json:"request_id"`

	// Status 物流状态
	Status *PostLogisticsTrackingJSONBodyStatus `json:"status,omitempty"`
}

// PostLogisticsTrackingJSONBodyStatus 物流状态
type PostLogisticsTrackingJSONBodyStatus string

// PutLogisticsTrackingIdJSONBody defines model for PutLogisticsTrackingIdJSONBody.
type PutLogisticsTrackingIdJSONBody struct {
	// Description 状态更新描述
	Description *string `json:"description,omitempty"`

	// Status 新的物流状态
	Status PutLogisticsTrackingIdJSONBodyStatus `json:"status"`
}

// PutLogisticsTrackingIdJSONBodyStatus 新的物流状态
type PutLogisticsTrackingIdJSONBodyStatus string

// Tracking defines model for Tracking.
type Tracking struct {
	// CreatedAt 创建时间
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Description 追踪描述
	Description *string `json:"description"`

	// Id 物流追踪ID
	Id *int `json:"id,omitempty"`

	// RequestId 关联的需求申报ID
	RequestId *int `json:"request_id,omitempty"`

	// Status 物流状态
	Status *TrackingStatus `json:"status,omitempty"`

	// TrackedAt 追踪时间
	TrackedAt *time.Time `json:"tracked_at"`

	// UpdatedAt 更新时间
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// TrackingStatus 物流状态
type TrackingStatus string

// PostLogisticsTrackingJSONRequestBody defines body for PostLogisticsTracking for application/json ContentType.
type PostLogisticsTrackingJSONRequestBody = PostLogisticsTrackingJSONBody

// PutLogisticsTrackingIdJSONRequestBody defines body for PutLogisticsTrackingId for application/json ContentType.
type PutLogisticsTrackingIdJSONRequestBody = PutLogisticsTrackingIdJSONBody
