// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: proto/logistics.proto

package logistics

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	LogisticsService_GetTracking_FullMethodName        = "/logistics.LogisticsService/GetTracking"
	LogisticsService_UpdateLocation_FullMethodName     = "/logistics.LogisticsService/UpdateLocation"
	LogisticsService_GetTrackingHistory_FullMethodName = "/logistics.LogisticsService/GetTrackingHistory"
	LogisticsService_CreateTracking_FullMethodName     = "/logistics.LogisticsService/CreateTracking"
)

// LogisticsServiceClient is the client API for LogisticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogisticsServiceClient interface {
	// 获取物流轨迹
	GetTracking(ctx context.Context, in *GetTrackingRequest, opts ...grpc.CallOption) (*GetTrackingResponse, error)
	// 更新物流位置
	UpdateLocation(ctx context.Context, in *UpdateLocationRequest, opts ...grpc.CallOption) (*UpdateLocationResponse, error)
	// 获取物流历史
	GetTrackingHistory(ctx context.Context, in *GetTrackingHistoryRequest, opts ...grpc.CallOption) (*GetTrackingHistoryResponse, error)
	// 创建物流记录
	CreateTracking(ctx context.Context, in *CreateTrackingRequest, opts ...grpc.CallOption) (*CreateTrackingResponse, error)
}

type logisticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogisticsServiceClient(cc grpc.ClientConnInterface) LogisticsServiceClient {
	return &logisticsServiceClient{cc}
}

func (c *logisticsServiceClient) GetTracking(ctx context.Context, in *GetTrackingRequest, opts ...grpc.CallOption) (*GetTrackingResponse, error) {
	out := new(GetTrackingResponse)
	err := c.cc.Invoke(ctx, LogisticsService_GetTracking_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logisticsServiceClient) UpdateLocation(ctx context.Context, in *UpdateLocationRequest, opts ...grpc.CallOption) (*UpdateLocationResponse, error) {
	out := new(UpdateLocationResponse)
	err := c.cc.Invoke(ctx, LogisticsService_UpdateLocation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logisticsServiceClient) GetTrackingHistory(ctx context.Context, in *GetTrackingHistoryRequest, opts ...grpc.CallOption) (*GetTrackingHistoryResponse, error) {
	out := new(GetTrackingHistoryResponse)
	err := c.cc.Invoke(ctx, LogisticsService_GetTrackingHistory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logisticsServiceClient) CreateTracking(ctx context.Context, in *CreateTrackingRequest, opts ...grpc.CallOption) (*CreateTrackingResponse, error) {
	out := new(CreateTrackingResponse)
	err := c.cc.Invoke(ctx, LogisticsService_CreateTracking_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogisticsServiceServer is the server API for LogisticsService service.
// All implementations should embed UnimplementedLogisticsServiceServer
// for forward compatibility
type LogisticsServiceServer interface {
	// 获取物流轨迹
	GetTracking(context.Context, *GetTrackingRequest) (*GetTrackingResponse, error)
	// 更新物流位置
	UpdateLocation(context.Context, *UpdateLocationRequest) (*UpdateLocationResponse, error)
	// 获取物流历史
	GetTrackingHistory(context.Context, *GetTrackingHistoryRequest) (*GetTrackingHistoryResponse, error)
	// 创建物流记录
	CreateTracking(context.Context, *CreateTrackingRequest) (*CreateTrackingResponse, error)
}

// UnimplementedLogisticsServiceServer should be embedded to have forward compatible implementations.
type UnimplementedLogisticsServiceServer struct {
}

func (UnimplementedLogisticsServiceServer) GetTracking(context.Context, *GetTrackingRequest) (*GetTrackingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTracking not implemented")
}
func (UnimplementedLogisticsServiceServer) UpdateLocation(context.Context, *UpdateLocationRequest) (*UpdateLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLocation not implemented")
}
func (UnimplementedLogisticsServiceServer) GetTrackingHistory(context.Context, *GetTrackingHistoryRequest) (*GetTrackingHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrackingHistory not implemented")
}
func (UnimplementedLogisticsServiceServer) CreateTracking(context.Context, *CreateTrackingRequest) (*CreateTrackingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTracking not implemented")
}

// UnsafeLogisticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogisticsServiceServer will
// result in compilation errors.
type UnsafeLogisticsServiceServer interface {
	mustEmbedUnimplementedLogisticsServiceServer()
}

func RegisterLogisticsServiceServer(s grpc.ServiceRegistrar, srv LogisticsServiceServer) {
	s.RegisterService(&LogisticsService_ServiceDesc, srv)
}

func _LogisticsService_GetTracking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrackingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogisticsServiceServer).GetTracking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogisticsService_GetTracking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogisticsServiceServer).GetTracking(ctx, req.(*GetTrackingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogisticsService_UpdateLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogisticsServiceServer).UpdateLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogisticsService_UpdateLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogisticsServiceServer).UpdateLocation(ctx, req.(*UpdateLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogisticsService_GetTrackingHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrackingHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogisticsServiceServer).GetTrackingHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogisticsService_GetTrackingHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogisticsServiceServer).GetTrackingHistory(ctx, req.(*GetTrackingHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogisticsService_CreateTracking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTrackingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogisticsServiceServer).CreateTracking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogisticsService_CreateTracking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogisticsServiceServer).CreateTracking(ctx, req.(*CreateTrackingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LogisticsService_ServiceDesc is the grpc.ServiceDesc for LogisticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogisticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logistics.LogisticsService",
	HandlerType: (*LogisticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTracking",
			Handler:    _LogisticsService_GetTracking_Handler,
		},
		{
			MethodName: "UpdateLocation",
			Handler:    _LogisticsService_UpdateLocation_Handler,
		},
		{
			MethodName: "GetTrackingHistory",
			Handler:    _LogisticsService_GetTrackingHistory_Handler,
		},
		{
			MethodName: "CreateTracking",
			Handler:    _LogisticsService_CreateTracking_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/logistics.proto",
}
