// Package statistics provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package statistics

import (
	"github.com/gin-gonic/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 获取统计报表
	// (GET /statistics/reports)
	GetStatisticsReports(c *gin.Context)
	// 获取统计汇总
	// (GET /statistics/summary)
	GetStatisticsSummary(c *gin.Context)
	// 获取统计趋势
	// (GET /statistics/trends)
	GetStatisticsTrends(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetStatisticsReports operation middleware
func (siw *ServerInterfaceWrapper) GetStatisticsReports(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStatisticsReports(c)
}

// GetStatisticsSummary operation middleware
func (siw *ServerInterfaceWrapper) GetStatisticsSummary(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStatisticsSummary(c)
}

// GetStatisticsTrends operation middleware
func (siw *ServerInterfaceWrapper) GetStatisticsTrends(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStatisticsTrends(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/statistics/reports", wrapper.GetStatisticsReports)
	router.GET(options.BaseURL+"/statistics/summary", wrapper.GetStatisticsSummary)
	router.GET(options.BaseURL+"/statistics/trends", wrapper.GetStatisticsTrends)
}
