// Package statistics provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package statistics

// MaterialStat defines model for MaterialStat.
type MaterialStat struct {
	Category *string `json:"category,omitempty"`
	Count    *int    `json:"count,omitempty"`
}

// RequestStat defines model for RequestStat.
type RequestStat struct {
	Count  *int    `json:"count,omitempty"`
	Status *string `json:"status,omitempty"`
}

// Summary defines model for Summary.
type Summary struct {
	CompletedRequests *int `json:"completed_requests,omitempty"`
	PendingRequests   *int `json:"pending_requests,omitempty"`
	TotalMaterials    *int `json:"total_materials,omitempty"`
	TotalRequests     *int `json:"total_requests,omitempty"`
}
