// Package stock provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package stock

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostStockInbound request
	PostStockInbound(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetStockInventory request
	GetStockInventory(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetStockMaterials request
	GetStockMaterials(ctx context.Context, params *GetStockMaterialsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostStockMaterialsWithBody request with any body
	PostStockMaterialsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostStockMaterials(ctx context.Context, body PostStockMaterialsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteStockMaterialsId request
	DeleteStockMaterialsId(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetStockMaterialsId request
	GetStockMaterialsId(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutStockMaterialsIdWithBody request with any body
	PutStockMaterialsIdWithBody(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutStockMaterialsId(ctx context.Context, id int, body PutStockMaterialsIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostStockOutbound request
	PostStockOutbound(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetStockStats request
	GetStockStats(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostStockTransfer request
	PostStockTransfer(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostStockInbound(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostStockInboundRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetStockInventory(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetStockInventoryRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetStockMaterials(ctx context.Context, params *GetStockMaterialsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetStockMaterialsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostStockMaterialsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostStockMaterialsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostStockMaterials(ctx context.Context, body PostStockMaterialsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostStockMaterialsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteStockMaterialsId(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteStockMaterialsIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetStockMaterialsId(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetStockMaterialsIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutStockMaterialsIdWithBody(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutStockMaterialsIdRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutStockMaterialsId(ctx context.Context, id int, body PutStockMaterialsIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutStockMaterialsIdRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostStockOutbound(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostStockOutboundRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetStockStats(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetStockStatsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostStockTransfer(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostStockTransferRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostStockInboundRequest generates requests for PostStockInbound
func NewPostStockInboundRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/stock/inbound")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetStockInventoryRequest generates requests for GetStockInventory
func NewGetStockInventoryRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/stock/inventory")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetStockMaterialsRequest generates requests for GetStockMaterials
func NewGetStockMaterialsRequest(server string, params *GetStockMaterialsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/stock/materials")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page", runtime.ParamLocationQuery, *params.Page); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PageSize != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page_size", runtime.ParamLocationQuery, *params.PageSize); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Search != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "search", runtime.ParamLocationQuery, *params.Search); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostStockMaterialsRequest calls the generic PostStockMaterials builder with application/json body
func NewPostStockMaterialsRequest(server string, body PostStockMaterialsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostStockMaterialsRequestWithBody(server, "application/json", bodyReader)
}

// NewPostStockMaterialsRequestWithBody generates requests for PostStockMaterials with any type of body
func NewPostStockMaterialsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/stock/materials")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteStockMaterialsIdRequest generates requests for DeleteStockMaterialsId
func NewDeleteStockMaterialsIdRequest(server string, id int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/stock/materials/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetStockMaterialsIdRequest generates requests for GetStockMaterialsId
func NewGetStockMaterialsIdRequest(server string, id int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/stock/materials/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutStockMaterialsIdRequest calls the generic PutStockMaterialsId builder with application/json body
func NewPutStockMaterialsIdRequest(server string, id int, body PutStockMaterialsIdJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutStockMaterialsIdRequestWithBody(server, id, "application/json", bodyReader)
}

// NewPutStockMaterialsIdRequestWithBody generates requests for PutStockMaterialsId with any type of body
func NewPutStockMaterialsIdRequestWithBody(server string, id int, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/stock/materials/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostStockOutboundRequest generates requests for PostStockOutbound
func NewPostStockOutboundRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/stock/outbound")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetStockStatsRequest generates requests for GetStockStats
func NewGetStockStatsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/stock/stats")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostStockTransferRequest generates requests for PostStockTransfer
func NewPostStockTransferRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/stock/transfer")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostStockInboundWithResponse request
	PostStockInboundWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostStockInboundResponse, error)

	// GetStockInventoryWithResponse request
	GetStockInventoryWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetStockInventoryResponse, error)

	// GetStockMaterialsWithResponse request
	GetStockMaterialsWithResponse(ctx context.Context, params *GetStockMaterialsParams, reqEditors ...RequestEditorFn) (*GetStockMaterialsResponse, error)

	// PostStockMaterialsWithBodyWithResponse request with any body
	PostStockMaterialsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostStockMaterialsResponse, error)

	PostStockMaterialsWithResponse(ctx context.Context, body PostStockMaterialsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostStockMaterialsResponse, error)

	// DeleteStockMaterialsIdWithResponse request
	DeleteStockMaterialsIdWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*DeleteStockMaterialsIdResponse, error)

	// GetStockMaterialsIdWithResponse request
	GetStockMaterialsIdWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*GetStockMaterialsIdResponse, error)

	// PutStockMaterialsIdWithBodyWithResponse request with any body
	PutStockMaterialsIdWithBodyWithResponse(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutStockMaterialsIdResponse, error)

	PutStockMaterialsIdWithResponse(ctx context.Context, id int, body PutStockMaterialsIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PutStockMaterialsIdResponse, error)

	// PostStockOutboundWithResponse request
	PostStockOutboundWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostStockOutboundResponse, error)

	// GetStockStatsWithResponse request
	GetStockStatsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetStockStatsResponse, error)

	// PostStockTransferWithResponse request
	PostStockTransferWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostStockTransferResponse, error)
}

type PostStockInboundResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostStockInboundResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostStockInboundResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetStockInventoryResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetStockInventoryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetStockInventoryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetStockMaterialsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetStockMaterialsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetStockMaterialsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostStockMaterialsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostStockMaterialsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostStockMaterialsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteStockMaterialsIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteStockMaterialsIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteStockMaterialsIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetStockMaterialsIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetStockMaterialsIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetStockMaterialsIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutStockMaterialsIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PutStockMaterialsIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutStockMaterialsIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostStockOutboundResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostStockOutboundResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostStockOutboundResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetStockStatsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetStockStatsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetStockStatsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostStockTransferResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostStockTransferResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostStockTransferResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostStockInboundWithResponse request returning *PostStockInboundResponse
func (c *ClientWithResponses) PostStockInboundWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostStockInboundResponse, error) {
	rsp, err := c.PostStockInbound(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostStockInboundResponse(rsp)
}

// GetStockInventoryWithResponse request returning *GetStockInventoryResponse
func (c *ClientWithResponses) GetStockInventoryWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetStockInventoryResponse, error) {
	rsp, err := c.GetStockInventory(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetStockInventoryResponse(rsp)
}

// GetStockMaterialsWithResponse request returning *GetStockMaterialsResponse
func (c *ClientWithResponses) GetStockMaterialsWithResponse(ctx context.Context, params *GetStockMaterialsParams, reqEditors ...RequestEditorFn) (*GetStockMaterialsResponse, error) {
	rsp, err := c.GetStockMaterials(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetStockMaterialsResponse(rsp)
}

// PostStockMaterialsWithBodyWithResponse request with arbitrary body returning *PostStockMaterialsResponse
func (c *ClientWithResponses) PostStockMaterialsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostStockMaterialsResponse, error) {
	rsp, err := c.PostStockMaterialsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostStockMaterialsResponse(rsp)
}

func (c *ClientWithResponses) PostStockMaterialsWithResponse(ctx context.Context, body PostStockMaterialsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostStockMaterialsResponse, error) {
	rsp, err := c.PostStockMaterials(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostStockMaterialsResponse(rsp)
}

// DeleteStockMaterialsIdWithResponse request returning *DeleteStockMaterialsIdResponse
func (c *ClientWithResponses) DeleteStockMaterialsIdWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*DeleteStockMaterialsIdResponse, error) {
	rsp, err := c.DeleteStockMaterialsId(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteStockMaterialsIdResponse(rsp)
}

// GetStockMaterialsIdWithResponse request returning *GetStockMaterialsIdResponse
func (c *ClientWithResponses) GetStockMaterialsIdWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*GetStockMaterialsIdResponse, error) {
	rsp, err := c.GetStockMaterialsId(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetStockMaterialsIdResponse(rsp)
}

// PutStockMaterialsIdWithBodyWithResponse request with arbitrary body returning *PutStockMaterialsIdResponse
func (c *ClientWithResponses) PutStockMaterialsIdWithBodyWithResponse(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutStockMaterialsIdResponse, error) {
	rsp, err := c.PutStockMaterialsIdWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutStockMaterialsIdResponse(rsp)
}

func (c *ClientWithResponses) PutStockMaterialsIdWithResponse(ctx context.Context, id int, body PutStockMaterialsIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PutStockMaterialsIdResponse, error) {
	rsp, err := c.PutStockMaterialsId(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutStockMaterialsIdResponse(rsp)
}

// PostStockOutboundWithResponse request returning *PostStockOutboundResponse
func (c *ClientWithResponses) PostStockOutboundWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostStockOutboundResponse, error) {
	rsp, err := c.PostStockOutbound(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostStockOutboundResponse(rsp)
}

// GetStockStatsWithResponse request returning *GetStockStatsResponse
func (c *ClientWithResponses) GetStockStatsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetStockStatsResponse, error) {
	rsp, err := c.GetStockStats(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetStockStatsResponse(rsp)
}

// PostStockTransferWithResponse request returning *PostStockTransferResponse
func (c *ClientWithResponses) PostStockTransferWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostStockTransferResponse, error) {
	rsp, err := c.PostStockTransfer(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostStockTransferResponse(rsp)
}

// ParsePostStockInboundResponse parses an HTTP response from a PostStockInboundWithResponse call
func ParsePostStockInboundResponse(rsp *http.Response) (*PostStockInboundResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostStockInboundResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetStockInventoryResponse parses an HTTP response from a GetStockInventoryWithResponse call
func ParseGetStockInventoryResponse(rsp *http.Response) (*GetStockInventoryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetStockInventoryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetStockMaterialsResponse parses an HTTP response from a GetStockMaterialsWithResponse call
func ParseGetStockMaterialsResponse(rsp *http.Response) (*GetStockMaterialsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetStockMaterialsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePostStockMaterialsResponse parses an HTTP response from a PostStockMaterialsWithResponse call
func ParsePostStockMaterialsResponse(rsp *http.Response) (*PostStockMaterialsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostStockMaterialsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseDeleteStockMaterialsIdResponse parses an HTTP response from a DeleteStockMaterialsIdWithResponse call
func ParseDeleteStockMaterialsIdResponse(rsp *http.Response) (*DeleteStockMaterialsIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteStockMaterialsIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetStockMaterialsIdResponse parses an HTTP response from a GetStockMaterialsIdWithResponse call
func ParseGetStockMaterialsIdResponse(rsp *http.Response) (*GetStockMaterialsIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetStockMaterialsIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePutStockMaterialsIdResponse parses an HTTP response from a PutStockMaterialsIdWithResponse call
func ParsePutStockMaterialsIdResponse(rsp *http.Response) (*PutStockMaterialsIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutStockMaterialsIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePostStockOutboundResponse parses an HTTP response from a PostStockOutboundWithResponse call
func ParsePostStockOutboundResponse(rsp *http.Response) (*PostStockOutboundResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostStockOutboundResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetStockStatsResponse parses an HTTP response from a GetStockStatsWithResponse call
func ParseGetStockStatsResponse(rsp *http.Response) (*GetStockStatsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetStockStatsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePostStockTransferResponse parses an HTTP response from a PostStockTransferWithResponse call
func ParsePostStockTransferResponse(rsp *http.Response) (*PostStockTransferResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostStockTransferResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}
