// Package stock provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package stock

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 物资入库
	// (POST /stock/inbound)
	PostStockInbound(c *gin.Context)
	// 获取库存信息
	// (GET /stock/inventory)
	GetStockInventory(c *gin.Context)
	// 获取物资列表
	// (GET /stock/materials)
	GetStockMaterials(c *gin.Context, params GetStockMaterialsParams)
	// 创建物资
	// (POST /stock/materials)
	PostStockMaterials(c *gin.Context)
	// 获取物资详情
	// (GET /stock/materials/{id})
	GetStockMaterialsId(c *gin.Context, id int)
	// 物资出库
	// (POST /stock/outbound)
	PostStockOutbound(c *gin.Context)
	// 库存统计
	// (GET /stock/stats)
	GetStockStats(c *gin.Context)
	// 库存调拨
	// (POST /stock/transfer)
	PostStockTransfer(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostStockInbound operation middleware
func (siw *ServerInterfaceWrapper) PostStockInbound(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostStockInbound(c)
}

// GetStockInventory operation middleware
func (siw *ServerInterfaceWrapper) GetStockInventory(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStockInventory(c)
}

// GetStockMaterials operation middleware
func (siw *ServerInterfaceWrapper) GetStockMaterials(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetStockMaterialsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page_size: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, false, "search", c.Request.URL.Query(), &params.Search)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter search: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStockMaterials(c, params)
}

// PostStockMaterials operation middleware
func (siw *ServerInterfaceWrapper) PostStockMaterials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostStockMaterials(c)
}

// GetStockMaterialsId operation middleware
func (siw *ServerInterfaceWrapper) GetStockMaterialsId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStockMaterialsId(c, id)
}

// PostStockOutbound operation middleware
func (siw *ServerInterfaceWrapper) PostStockOutbound(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostStockOutbound(c)
}

// GetStockStats operation middleware
func (siw *ServerInterfaceWrapper) GetStockStats(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStockStats(c)
}

// PostStockTransfer operation middleware
func (siw *ServerInterfaceWrapper) PostStockTransfer(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostStockTransfer(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/stock/inbound", wrapper.PostStockInbound)
	router.GET(options.BaseURL+"/stock/inventory", wrapper.GetStockInventory)
	router.GET(options.BaseURL+"/stock/materials", wrapper.GetStockMaterials)
	router.POST(options.BaseURL+"/stock/materials", wrapper.PostStockMaterials)
	router.GET(options.BaseURL+"/stock/materials/:id", wrapper.GetStockMaterialsId)
	router.POST(options.BaseURL+"/stock/outbound", wrapper.PostStockOutbound)
	router.GET(options.BaseURL+"/stock/stats", wrapper.GetStockStats)
	router.POST(options.BaseURL+"/stock/transfer", wrapper.PostStockTransfer)
}
