// Package dispatch provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package dispatch

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetDispatchRequests request
	GetDispatchRequests(ctx context.Context, params *GetDispatchRequestsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostDispatchRequestsWithBody request with any body
	PostDispatchRequestsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostDispatchRequests(ctx context.Context, body PostDispatchRequestsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDispatchRequestsId request
	GetDispatchRequestsId(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDispatchRequestsIdAllocationSuggestion request
	GetDispatchRequestsIdAllocationSuggestion(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostDispatchRequestsIdAuditWithBody request with any body
	PostDispatchRequestsIdAuditWithBody(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostDispatchRequestsIdAudit(ctx context.Context, id int, body PostDispatchRequestsIdAuditJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDispatchTasks request
	GetDispatchTasks(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostDispatchTasksWithBody request with any body
	PostDispatchTasksWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostDispatchTasks(ctx context.Context, body PostDispatchTasksJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetDispatchRequests(ctx context.Context, params *GetDispatchRequestsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDispatchRequestsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostDispatchRequestsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostDispatchRequestsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostDispatchRequests(ctx context.Context, body PostDispatchRequestsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostDispatchRequestsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetDispatchRequestsId(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDispatchRequestsIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetDispatchRequestsIdAllocationSuggestion(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDispatchRequestsIdAllocationSuggestionRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostDispatchRequestsIdAuditWithBody(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostDispatchRequestsIdAuditRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostDispatchRequestsIdAudit(ctx context.Context, id int, body PostDispatchRequestsIdAuditJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostDispatchRequestsIdAuditRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetDispatchTasks(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDispatchTasksRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostDispatchTasksWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostDispatchTasksRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostDispatchTasks(ctx context.Context, body PostDispatchTasksJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostDispatchTasksRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetDispatchRequestsRequest generates requests for GetDispatchRequests
func NewGetDispatchRequestsRequest(server string, params *GetDispatchRequestsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/dispatch/requests")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page", runtime.ParamLocationQuery, *params.Page); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PageSize != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page_size", runtime.ParamLocationQuery, *params.PageSize); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Status != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "status", runtime.ParamLocationQuery, *params.Status); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostDispatchRequestsRequest calls the generic PostDispatchRequests builder with application/json body
func NewPostDispatchRequestsRequest(server string, body PostDispatchRequestsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostDispatchRequestsRequestWithBody(server, "application/json", bodyReader)
}

// NewPostDispatchRequestsRequestWithBody generates requests for PostDispatchRequests with any type of body
func NewPostDispatchRequestsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/dispatch/requests")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetDispatchRequestsIdRequest generates requests for GetDispatchRequestsId
func NewGetDispatchRequestsIdRequest(server string, id int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/dispatch/requests/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetDispatchRequestsIdAllocationSuggestionRequest generates requests for GetDispatchRequestsIdAllocationSuggestion
func NewGetDispatchRequestsIdAllocationSuggestionRequest(server string, id int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/dispatch/requests/%s/allocation-suggestion", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostDispatchRequestsIdAuditRequest calls the generic PostDispatchRequestsIdAudit builder with application/json body
func NewPostDispatchRequestsIdAuditRequest(server string, id int, body PostDispatchRequestsIdAuditJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostDispatchRequestsIdAuditRequestWithBody(server, id, "application/json", bodyReader)
}

// NewPostDispatchRequestsIdAuditRequestWithBody generates requests for PostDispatchRequestsIdAudit with any type of body
func NewPostDispatchRequestsIdAuditRequestWithBody(server string, id int, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/dispatch/requests/%s/audit", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetDispatchTasksRequest generates requests for GetDispatchTasks
func NewGetDispatchTasksRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/dispatch/tasks")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostDispatchTasksRequest calls the generic PostDispatchTasks builder with application/json body
func NewPostDispatchTasksRequest(server string, body PostDispatchTasksJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostDispatchTasksRequestWithBody(server, "application/json", bodyReader)
}

// NewPostDispatchTasksRequestWithBody generates requests for PostDispatchTasks with any type of body
func NewPostDispatchTasksRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/dispatch/tasks")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetDispatchRequestsWithResponse request
	GetDispatchRequestsWithResponse(ctx context.Context, params *GetDispatchRequestsParams, reqEditors ...RequestEditorFn) (*GetDispatchRequestsResponse, error)

	// PostDispatchRequestsWithBodyWithResponse request with any body
	PostDispatchRequestsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostDispatchRequestsResponse, error)

	PostDispatchRequestsWithResponse(ctx context.Context, body PostDispatchRequestsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostDispatchRequestsResponse, error)

	// GetDispatchRequestsIdWithResponse request
	GetDispatchRequestsIdWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*GetDispatchRequestsIdResponse, error)

	// GetDispatchRequestsIdAllocationSuggestionWithResponse request
	GetDispatchRequestsIdAllocationSuggestionWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*GetDispatchRequestsIdAllocationSuggestionResponse, error)

	// PostDispatchRequestsIdAuditWithBodyWithResponse request with any body
	PostDispatchRequestsIdAuditWithBodyWithResponse(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostDispatchRequestsIdAuditResponse, error)

	PostDispatchRequestsIdAuditWithResponse(ctx context.Context, id int, body PostDispatchRequestsIdAuditJSONRequestBody, reqEditors ...RequestEditorFn) (*PostDispatchRequestsIdAuditResponse, error)

	// GetDispatchTasksWithResponse request
	GetDispatchTasksWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetDispatchTasksResponse, error)

	// PostDispatchTasksWithBodyWithResponse request with any body
	PostDispatchTasksWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostDispatchTasksResponse, error)

	PostDispatchTasksWithResponse(ctx context.Context, body PostDispatchTasksJSONRequestBody, reqEditors ...RequestEditorFn) (*PostDispatchTasksResponse, error)
}

type GetDispatchRequestsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetDispatchRequestsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDispatchRequestsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostDispatchRequestsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostDispatchRequestsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostDispatchRequestsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetDispatchRequestsIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetDispatchRequestsIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDispatchRequestsIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetDispatchRequestsIdAllocationSuggestionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetDispatchRequestsIdAllocationSuggestionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDispatchRequestsIdAllocationSuggestionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostDispatchRequestsIdAuditResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostDispatchRequestsIdAuditResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostDispatchRequestsIdAuditResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetDispatchTasksResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetDispatchTasksResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDispatchTasksResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostDispatchTasksResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostDispatchTasksResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostDispatchTasksResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetDispatchRequestsWithResponse request returning *GetDispatchRequestsResponse
func (c *ClientWithResponses) GetDispatchRequestsWithResponse(ctx context.Context, params *GetDispatchRequestsParams, reqEditors ...RequestEditorFn) (*GetDispatchRequestsResponse, error) {
	rsp, err := c.GetDispatchRequests(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDispatchRequestsResponse(rsp)
}

// PostDispatchRequestsWithBodyWithResponse request with arbitrary body returning *PostDispatchRequestsResponse
func (c *ClientWithResponses) PostDispatchRequestsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostDispatchRequestsResponse, error) {
	rsp, err := c.PostDispatchRequestsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostDispatchRequestsResponse(rsp)
}

func (c *ClientWithResponses) PostDispatchRequestsWithResponse(ctx context.Context, body PostDispatchRequestsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostDispatchRequestsResponse, error) {
	rsp, err := c.PostDispatchRequests(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostDispatchRequestsResponse(rsp)
}

// GetDispatchRequestsIdWithResponse request returning *GetDispatchRequestsIdResponse
func (c *ClientWithResponses) GetDispatchRequestsIdWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*GetDispatchRequestsIdResponse, error) {
	rsp, err := c.GetDispatchRequestsId(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDispatchRequestsIdResponse(rsp)
}

// GetDispatchRequestsIdAllocationSuggestionWithResponse request returning *GetDispatchRequestsIdAllocationSuggestionResponse
func (c *ClientWithResponses) GetDispatchRequestsIdAllocationSuggestionWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*GetDispatchRequestsIdAllocationSuggestionResponse, error) {
	rsp, err := c.GetDispatchRequestsIdAllocationSuggestion(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDispatchRequestsIdAllocationSuggestionResponse(rsp)
}

// PostDispatchRequestsIdAuditWithBodyWithResponse request with arbitrary body returning *PostDispatchRequestsIdAuditResponse
func (c *ClientWithResponses) PostDispatchRequestsIdAuditWithBodyWithResponse(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostDispatchRequestsIdAuditResponse, error) {
	rsp, err := c.PostDispatchRequestsIdAuditWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostDispatchRequestsIdAuditResponse(rsp)
}

func (c *ClientWithResponses) PostDispatchRequestsIdAuditWithResponse(ctx context.Context, id int, body PostDispatchRequestsIdAuditJSONRequestBody, reqEditors ...RequestEditorFn) (*PostDispatchRequestsIdAuditResponse, error) {
	rsp, err := c.PostDispatchRequestsIdAudit(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostDispatchRequestsIdAuditResponse(rsp)
}

// GetDispatchTasksWithResponse request returning *GetDispatchTasksResponse
func (c *ClientWithResponses) GetDispatchTasksWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetDispatchTasksResponse, error) {
	rsp, err := c.GetDispatchTasks(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDispatchTasksResponse(rsp)
}

// PostDispatchTasksWithBodyWithResponse request with arbitrary body returning *PostDispatchTasksResponse
func (c *ClientWithResponses) PostDispatchTasksWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostDispatchTasksResponse, error) {
	rsp, err := c.PostDispatchTasksWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostDispatchTasksResponse(rsp)
}

func (c *ClientWithResponses) PostDispatchTasksWithResponse(ctx context.Context, body PostDispatchTasksJSONRequestBody, reqEditors ...RequestEditorFn) (*PostDispatchTasksResponse, error) {
	rsp, err := c.PostDispatchTasks(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostDispatchTasksResponse(rsp)
}

// ParseGetDispatchRequestsResponse parses an HTTP response from a GetDispatchRequestsWithResponse call
func ParseGetDispatchRequestsResponse(rsp *http.Response) (*GetDispatchRequestsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDispatchRequestsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePostDispatchRequestsResponse parses an HTTP response from a PostDispatchRequestsWithResponse call
func ParsePostDispatchRequestsResponse(rsp *http.Response) (*PostDispatchRequestsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostDispatchRequestsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetDispatchRequestsIdResponse parses an HTTP response from a GetDispatchRequestsIdWithResponse call
func ParseGetDispatchRequestsIdResponse(rsp *http.Response) (*GetDispatchRequestsIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDispatchRequestsIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetDispatchRequestsIdAllocationSuggestionResponse parses an HTTP response from a GetDispatchRequestsIdAllocationSuggestionWithResponse call
func ParseGetDispatchRequestsIdAllocationSuggestionResponse(rsp *http.Response) (*GetDispatchRequestsIdAllocationSuggestionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDispatchRequestsIdAllocationSuggestionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePostDispatchRequestsIdAuditResponse parses an HTTP response from a PostDispatchRequestsIdAuditWithResponse call
func ParsePostDispatchRequestsIdAuditResponse(rsp *http.Response) (*PostDispatchRequestsIdAuditResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostDispatchRequestsIdAuditResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetDispatchTasksResponse parses an HTTP response from a GetDispatchTasksWithResponse call
func ParseGetDispatchTasksResponse(rsp *http.Response) (*GetDispatchTasksResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDispatchTasksResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePostDispatchTasksResponse parses an HTTP response from a PostDispatchTasksWithResponse call
func ParsePostDispatchTasksResponse(rsp *http.Response) (*PostDispatchTasksResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostDispatchTasksResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}
