// Package dispatch provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package dispatch

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 获取需求申报列表
	// (GET /dispatch/requests)
	GetDispatchRequests(c *gin.Context, params GetDispatchRequestsParams)
	// 创建需求申报
	// (POST /dispatch/requests)
	PostDispatchRequests(c *gin.Context)
	// 获取需求单详情
	// (GET /dispatch/requests/{id})
	GetDispatchRequestsId(c *gin.Context, id int)
	// 获取智能分配建议
	// (GET /dispatch/requests/{id}/allocation-suggestion)
	GetDispatchRequestsIdAllocationSuggestion(c *gin.Context, id int)
	// 审核需求单
	// (POST /dispatch/requests/{id}/audit)
	PostDispatchRequestsIdAudit(c *gin.Context, id int)
	// 获取配送任务列表
	// (GET /dispatch/tasks)
	GetDispatchTasks(c *gin.Context)
	// 创建配送任务 (原子化执行分配与锁库)
	// (POST /dispatch/tasks)
	PostDispatchTasks(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetDispatchRequests operation middleware
func (siw *ServerInterfaceWrapper) GetDispatchRequests(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDispatchRequestsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page_size: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", c.Request.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDispatchRequests(c, params)
}

// PostDispatchRequests operation middleware
func (siw *ServerInterfaceWrapper) PostDispatchRequests(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostDispatchRequests(c)
}

// GetDispatchRequestsId operation middleware
func (siw *ServerInterfaceWrapper) GetDispatchRequestsId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDispatchRequestsId(c, id)
}

// GetDispatchRequestsIdAllocationSuggestion operation middleware
func (siw *ServerInterfaceWrapper) GetDispatchRequestsIdAllocationSuggestion(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDispatchRequestsIdAllocationSuggestion(c, id)
}

// PostDispatchRequestsIdAudit operation middleware
func (siw *ServerInterfaceWrapper) PostDispatchRequestsIdAudit(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostDispatchRequestsIdAudit(c, id)
}

// GetDispatchTasks operation middleware
func (siw *ServerInterfaceWrapper) GetDispatchTasks(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDispatchTasks(c)
}

// PostDispatchTasks operation middleware
func (siw *ServerInterfaceWrapper) PostDispatchTasks(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostDispatchTasks(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/dispatch/requests", wrapper.GetDispatchRequests)
	router.POST(options.BaseURL+"/dispatch/requests", wrapper.PostDispatchRequests)
	router.GET(options.BaseURL+"/dispatch/requests/:id", wrapper.GetDispatchRequestsId)
	router.GET(options.BaseURL+"/dispatch/requests/:id/allocation-suggestion", wrapper.GetDispatchRequestsIdAllocationSuggestion)
	router.POST(options.BaseURL+"/dispatch/requests/:id/audit", wrapper.PostDispatchRequestsIdAudit)
	router.GET(options.BaseURL+"/dispatch/tasks", wrapper.GetDispatchTasks)
	router.POST(options.BaseURL+"/dispatch/tasks", wrapper.PostDispatchTasks)
}
