// Package dispatch provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package dispatch

import (
	"time"
)

// Defines values for PostDispatchRequestsJSONBodyUrgencyLevel.
const (
	PostDispatchRequestsJSONBodyUrgencyLevelHigh   PostDispatchRequestsJSONBodyUrgencyLevel = "high"
	PostDispatchRequestsJSONBodyUrgencyLevelLow    PostDispatchRequestsJSONBodyUrgencyLevel = "low"
	PostDispatchRequestsJSONBodyUrgencyLevelMedium PostDispatchRequestsJSONBodyUrgencyLevel = "medium"
	PostDispatchRequestsJSONBodyUrgencyLevelUrgent PostDispatchRequestsJSONBodyUrgencyLevel = "urgent"
)

// Defines values for PutDispatchRequestsIdStatusJSONBodyStatus.
const (
	PutDispatchRequestsIdStatusJSONBodyStatusApproved  PutDispatchRequestsIdStatusJSONBodyStatus = "approved"
	PutDispatchRequestsIdStatusJSONBodyStatusCompleted PutDispatchRequestsIdStatusJSONBodyStatus = "completed"
	PutDispatchRequestsIdStatusJSONBodyStatusPending   PutDispatchRequestsIdStatusJSONBodyStatus = "pending"
	PutDispatchRequestsIdStatusJSONBodyStatusRejected  PutDispatchRequestsIdStatusJSONBodyStatus = "rejected"
)

// Defines values for RequestStatus.
const (
	RequestStatusApproved  RequestStatus = "approved"
	RequestStatusCompleted RequestStatus = "completed"
	RequestStatusPending   RequestStatus = "pending"
	RequestStatusRejected  RequestStatus = "rejected"
)

// Defines values for RequestUrgencyLevel.
const (
	RequestUrgencyLevelHigh   RequestUrgencyLevel = "high"
	RequestUrgencyLevelLow    RequestUrgencyLevel = "low"
	RequestUrgencyLevelMedium RequestUrgencyLevel = "medium"
	RequestUrgencyLevelUrgent RequestUrgencyLevel = "urgent"
)

// Error defines model for Error.
type Error struct {
	// Error 错误信息
	Error *string `json:"error,omitempty"`
}

// PostDispatchRequestsJSONBody defines model for PostDispatchRequestsJSONBody.
type PostDispatchRequestsJSONBody struct {
	// Description 需求描述
	Description *string `json:"description,omitempty"`

	// MaterialId 物资ID
	MaterialId int `json:"material_id"`

	// Quantity 需求数量
	Quantity int `json:"quantity"`

	// RequesterId 申报人ID
	RequesterId int `json:"requester_id"`

	// UrgencyLevel 紧急程度
	UrgencyLevel *PostDispatchRequestsJSONBodyUrgencyLevel `json:"urgency_level,omitempty"`
}

// PostDispatchRequestsJSONBodyUrgencyLevel 紧急程度
type PostDispatchRequestsJSONBodyUrgencyLevel string

// PutDispatchRequestsIdStatusJSONBody defines model for PutDispatchRequestsIdStatusJSONBody.
type PutDispatchRequestsIdStatusJSONBody struct {
	// Status 新状态
	Status PutDispatchRequestsIdStatusJSONBodyStatus `json:"status"`
}

// PutDispatchRequestsIdStatusJSONBodyStatus 新状态
type PutDispatchRequestsIdStatusJSONBodyStatus string

// Request defines model for Request.
type Request struct {
	// CreatedAt 创建时间
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Description 需求描述
	Description *string `json:"description"`

	// Id 需求申报ID
	Id *int `json:"id,omitempty"`

	// MaterialId 物资ID
	MaterialId *int `json:"material_id"`

	// Quantity 需求数量
	Quantity *int `json:"quantity"`

	// RequesterId 申报人ID
	RequesterId *int `json:"requester_id"`

	// Status 申报状态
	Status *RequestStatus `json:"status,omitempty"`

	// UpdatedAt 更新时间
	UpdatedAt *time.Time `json:"updated_at,omitempty"`

	// UrgencyLevel 紧急程度
	UrgencyLevel *RequestUrgencyLevel `json:"urgency_level"`
}

// RequestStatus 申报状态
type RequestStatus string

// RequestUrgencyLevel 紧急程度
type RequestUrgencyLevel string

// GetDispatchRequestsParams defines parameters for GetDispatchRequests.
type GetDispatchRequestsParams struct {
	// Page 页码，从1开始
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize 每页记录数
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// PostDispatchRequestsJSONRequestBody defines body for PostDispatchRequests for application/json ContentType.
type PostDispatchRequestsJSONRequestBody = PostDispatchRequestsJSONBody

// PutDispatchRequestsIdJSONRequestBody defines body for PutDispatchRequestsId for application/json ContentType.
type PutDispatchRequestsIdJSONRequestBody = PutDispatchRequestsIdStatusJSONBody
