openapi: 3.0.0
info:
  title: Auth API
  version: 1.0.0
  description: 认证与权限服务 API

paths:
  /auth/login:
    post:
      summary: 用户登录
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: 登录成功
        '401':
          description: 认证失败

  /auth/logout:
    post:
      summary: 用户登出
      tags:
        - Auth
      responses:
        '200':
          description: 登出成功

  /auth/refresh:
    post:
      summary: 刷新令牌
      tags:
        - Auth
      responses:
        '200':
          description: 刷新成功

