openapi: 3.0.0
info:
  title: Auth API
  version: 1.0.0
  description: 认证与权限服务 API

paths:
  /auth/register:
    post:
      summary: 用户注册
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
                - email
                - phone
                - roles
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
                phone:
                  type: string
                roles:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: 注册成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  message:
                    type: string
        '400':
          description: 参数错误

  /auth/login:
    post:
      summary: 用户登录
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: 登录成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  refresh_token:
                    type: string
                  expires_in:
                    type: integer
        '401':
          description: 认证失败

  /auth/logout:
    post:
      summary: 用户登出
      tags:
        - Auth
      responses:
        '200':
          description: 登出成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /auth/refresh:
    post:
      summary: 刷新令牌
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh_token:
                  type: string
                  description: 刷新令牌
              required:
                - refresh_token
      responses:
        '200':
          description: 刷新成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  refresh_token:
                    type: string
                  expires_in:
                    type: integer
        '401':
          description: 无效的刷新令牌