openapi: 3.0.0
info:
  title: Statistics API
  version: 1.0.0
  description: 统计分析服务 API

paths:
  /statistics/summary:
    get:
      summary: 获取统计摘要
      tags:
        - Statistics
      responses:
        '200':
          description: 成功返回统计摘要

  /statistics/reports:
    get:
      summary: 获取报表数据
      tags:
        - Statistics
      responses:
        '200':
          description: 成功返回报表数据

  /statistics/trends:
    get:
      summary: 获取趋势分析
      tags:
        - Statistics
      responses:
        '200':
          description: 成功返回趋势数据

