// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: dispatch.proto

package dispatch

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DispatchService_ListDemands_FullMethodName         = "/dispatch.DispatchService/ListDemands"
	DispatchService_CreateDemand_FullMethodName        = "/dispatch.DispatchService/CreateDemand"
	DispatchService_GetDemand_FullMethodName           = "/dispatch.DispatchService/GetDemand"
	DispatchService_UpdateDemandStatus_FullMethodName  = "/dispatch.DispatchService/UpdateDemandStatus"
	DispatchService_CreateDispatchOrder_FullMethodName = "/dispatch.DispatchService/CreateDispatchOrder"
	DispatchService_ListDispatchOrders_FullMethodName  = "/dispatch.DispatchService/ListDispatchOrders"
)

// DispatchServiceClient is the client API for DispatchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DispatchServiceClient interface {
	ListDemands(ctx context.Context, in *ListDemandsRequest, opts ...grpc.CallOption) (*ListDemandsResponse, error)
	CreateDemand(ctx context.Context, in *CreateDemandRequest, opts ...grpc.CallOption) (*CreateDemandResponse, error)
	GetDemand(ctx context.Context, in *GetDemandRequest, opts ...grpc.CallOption) (*GetDemandResponse, error)
	UpdateDemandStatus(ctx context.Context, in *UpdateDemandStatusRequest, opts ...grpc.CallOption) (*UpdateDemandStatusResponse, error)
	CreateDispatchOrder(ctx context.Context, in *CreateDispatchOrderRequest, opts ...grpc.CallOption) (*CreateDispatchOrderResponse, error)
	ListDispatchOrders(ctx context.Context, in *ListDispatchOrdersRequest, opts ...grpc.CallOption) (*ListDispatchOrdersResponse, error)
}

type dispatchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDispatchServiceClient(cc grpc.ClientConnInterface) DispatchServiceClient {
	return &dispatchServiceClient{cc}
}

func (c *dispatchServiceClient) ListDemands(ctx context.Context, in *ListDemandsRequest, opts ...grpc.CallOption) (*ListDemandsResponse, error) {
	out := new(ListDemandsResponse)
	err := c.cc.Invoke(ctx, DispatchService_ListDemands_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatchServiceClient) CreateDemand(ctx context.Context, in *CreateDemandRequest, opts ...grpc.CallOption) (*CreateDemandResponse, error) {
	out := new(CreateDemandResponse)
	err := c.cc.Invoke(ctx, DispatchService_CreateDemand_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatchServiceClient) GetDemand(ctx context.Context, in *GetDemandRequest, opts ...grpc.CallOption) (*GetDemandResponse, error) {
	out := new(GetDemandResponse)
	err := c.cc.Invoke(ctx, DispatchService_GetDemand_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatchServiceClient) UpdateDemandStatus(ctx context.Context, in *UpdateDemandStatusRequest, opts ...grpc.CallOption) (*UpdateDemandStatusResponse, error) {
	out := new(UpdateDemandStatusResponse)
	err := c.cc.Invoke(ctx, DispatchService_UpdateDemandStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatchServiceClient) CreateDispatchOrder(ctx context.Context, in *CreateDispatchOrderRequest, opts ...grpc.CallOption) (*CreateDispatchOrderResponse, error) {
	out := new(CreateDispatchOrderResponse)
	err := c.cc.Invoke(ctx, DispatchService_CreateDispatchOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatchServiceClient) ListDispatchOrders(ctx context.Context, in *ListDispatchOrdersRequest, opts ...grpc.CallOption) (*ListDispatchOrdersResponse, error) {
	out := new(ListDispatchOrdersResponse)
	err := c.cc.Invoke(ctx, DispatchService_ListDispatchOrders_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DispatchServiceServer is the server API for DispatchService service.
// All implementations must embed UnimplementedDispatchServiceServer
// for forward compatibility
type DispatchServiceServer interface {
	ListDemands(context.Context, *ListDemandsRequest) (*ListDemandsResponse, error)
	CreateDemand(context.Context, *CreateDemandRequest) (*CreateDemandResponse, error)
	GetDemand(context.Context, *GetDemandRequest) (*GetDemandResponse, error)
	UpdateDemandStatus(context.Context, *UpdateDemandStatusRequest) (*UpdateDemandStatusResponse, error)
	CreateDispatchOrder(context.Context, *CreateDispatchOrderRequest) (*CreateDispatchOrderResponse, error)
	ListDispatchOrders(context.Context, *ListDispatchOrdersRequest) (*ListDispatchOrdersResponse, error)
	mustEmbedUnimplementedDispatchServiceServer()
}

// UnimplementedDispatchServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDispatchServiceServer struct {
}

func (UnimplementedDispatchServiceServer) ListDemands(context.Context, *ListDemandsRequest) (*ListDemandsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDemands not implemented")
}
func (UnimplementedDispatchServiceServer) CreateDemand(context.Context, *CreateDemandRequest) (*CreateDemandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDemand not implemented")
}
func (UnimplementedDispatchServiceServer) GetDemand(context.Context, *GetDemandRequest) (*GetDemandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDemand not implemented")
}
func (UnimplementedDispatchServiceServer) UpdateDemandStatus(context.Context, *UpdateDemandStatusRequest) (*UpdateDemandStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDemandStatus not implemented")
}
func (UnimplementedDispatchServiceServer) CreateDispatchOrder(context.Context, *CreateDispatchOrderRequest) (*CreateDispatchOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDispatchOrder not implemented")
}
func (UnimplementedDispatchServiceServer) ListDispatchOrders(context.Context, *ListDispatchOrdersRequest) (*ListDispatchOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDispatchOrders not implemented")
}
func (UnimplementedDispatchServiceServer) mustEmbedUnimplementedDispatchServiceServer() {}

// UnsafeDispatchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DispatchServiceServer will
// result in compilation errors.
type UnsafeDispatchServiceServer interface {
	mustEmbedUnimplementedDispatchServiceServer()
}

func RegisterDispatchServiceServer(s grpc.ServiceRegistrar, srv DispatchServiceServer) {
	s.RegisterService(&DispatchService_ServiceDesc, srv)
}

func _DispatchService_ListDemands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDemandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServiceServer).ListDemands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DispatchService_ListDemands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServiceServer).ListDemands(ctx, req.(*ListDemandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DispatchService_CreateDemand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDemandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServiceServer).CreateDemand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DispatchService_CreateDemand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServiceServer).CreateDemand(ctx, req.(*CreateDemandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DispatchService_GetDemand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDemandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServiceServer).GetDemand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DispatchService_GetDemand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServiceServer).GetDemand(ctx, req.(*GetDemandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DispatchService_UpdateDemandStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDemandStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServiceServer).UpdateDemandStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DispatchService_UpdateDemandStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServiceServer).UpdateDemandStatus(ctx, req.(*UpdateDemandStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DispatchService_CreateDispatchOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDispatchOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServiceServer).CreateDispatchOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DispatchService_CreateDispatchOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServiceServer).CreateDispatchOrder(ctx, req.(*CreateDispatchOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DispatchService_ListDispatchOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDispatchOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServiceServer).ListDispatchOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DispatchService_ListDispatchOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServiceServer).ListDispatchOrders(ctx, req.(*ListDispatchOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DispatchService_ServiceDesc is the grpc.ServiceDesc for DispatchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DispatchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dispatch.DispatchService",
	HandlerType: (*DispatchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDemands",
			Handler:    _DispatchService_ListDemands_Handler,
		},
		{
			MethodName: "CreateDemand",
			Handler:    _DispatchService_CreateDemand_Handler,
		},
		{
			MethodName: "GetDemand",
			Handler:    _DispatchService_GetDemand_Handler,
		},
		{
			MethodName: "UpdateDemandStatus",
			Handler:    _DispatchService_UpdateDemandStatus_Handler,
		},
		{
			MethodName: "CreateDispatchOrder",
			Handler:    _DispatchService_CreateDispatchOrder_Handler,
		},
		{
			MethodName: "ListDispatchOrders",
			Handler:    _DispatchService_ListDispatchOrders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dispatch.proto",
}
